### ISSUE TITLE
RuntimeError: CUDA out of memory

### ISSUE THREAD

**Issue by naittaleb** [romi/Segmentation#2]
- Machine learning pipe cannot run on middle GPU machines
 - Check if we can reduce graphical memory consumption

**Comment by fabfabBesnard** [comment]
**Reproducible example**:
data available on AWS server: `~/database_fabfab/test_Sangoku/Sangoku_mlpipe_1` 
72 images taken with RX-0 camera on the dev robot plant imager in Lyon of the 3D printed plant model generated from a Lpy virtual plant.

**Run**: docker container using the following image of plant-3d-vision (image built from branch `Fix/VisualizationTaskForVirtualData`): 
```
REPOSITORY               TAG                 IMAGE ID            CREATED             SIZE
plant3dvision            Visu_VP             11b1d7e662b8        10 days ago         7.77GB
```
**command line**: `romi_run_task AnglesAndInternodes --config database/ml_pipe_real_default.toml database/Sangoku_mlpipe_1`

**Result** (run & error log):
```
INFO     [luigi-interface] [pid 1837] Worker Worker(salt=351061715, workers=1, host=9d60680
9db6a, username=scanner, pid=1837) running   Segmentation2D(scan_id=, upstream_task=Undisto
rted, model_fileset=ModelFileset, model_id=Resnet_896_896_epoch50, query={"channel": "rgb"}
, Sx=896, Sy=896, labels=[], inverted_labels=["background"], binarize=True, threshold=0.01,
 dilation=1) from fileConfig
^M  0%|          | 0/72 [00:00<?, ?it/s]^M  1%|▏         | 1/72 [00:00<00:57,  1.23it/s]^M  3%|▎         | 2/72 [00:01<01:01,  1.14it/s]^M  4%|▍         | 3/72 [00:02<00:59,  1.15it/s]^M  6%|▌         | 4/72 [00:03<00:58,  1.17it/s]^M  7%|▋         | 5/72 [00:04<00:56,  1.19it/s]^M  8%|▊         | 6/72 [00:05<00:54,  1.21it/s]^M 10%|▉         | 7/72 [00:05<00:53,  1.22it/s]^M 11%|█         | 8/72 [00:06<00:52,  1.23it/s]^M 12%|█▎        | 9/72 [00:07<00:51,  1.24it/s]^M 14%|█▍        | 10/72 [00:08<00:50,  1.24it/s]^M 15%|█▌        | 11/72 [00:09<00:49,  1.24it/s]^M 17%|█▋        | 12/72 [00:09<00:48,  1.24it/s]^M 18%|█▊        | 13/72 [00:10<00:47,  1.24it/s]^M 19%|█▉        | 14/72 [00:11<00:46,  1.24it/s]^M 21%|██        | 15/72 [00:12<00:45,  1.24it/s]^M 22%|██▏       | 16/72 [00:13<00:45,  1.24it/s]^M 24%|██▎       | 17/72 [00:13<00:44,  1.24it/s]^M 25%|██▌       | 18/72 [00:14<00:43,  1.24it/s]^M 26%|██▋       | 19/72 [00:15<00:42,  1.24it/s]^M 28%|██▊       | 20/72 [00:16<00:41,  1.24it/s]^M 29%|██▉       | 21/72 [00:17<00:40,  1.24it/s]^M 31%|███       | 22/72 [00:17<00:40,  1.24it/s]^M 32%|███▏      | 23/72 [00:18<00:39,  1.24it/s]^M 33%|███▎      | 24/72 [00:19<00:38,  1.24it/s]^M 35%|███▍      | 25/72 [00:20<00:37,  1.24it/s]^M 36%|███▌      | 26/72 [00:21<00:37,  1.24it/s]^M 38%|███▊      | 27/72 [00:21<00:36,  1.24it/s]^M 39%|███▉      | 28/72 [00:22<00:35,  1.25it/s]^M 40%|████      | 29/72 [00:23<00:34,  1.25it/s]^M 42%|████▏     | 30/72 [00:25<00:42,  1.01s/it]^M 43%|████▎     | 31/72 [00:25<00:36,  1.11it/s]^M 43%|████▎     | 31/72 [00:27<00:35,  1.14it/s]
ERROR    [luigi-interface] [pid 1837] Worker Worker(salt=351061715, workers=1, host=9d606809db6a, username=scanner, pid=1837) failed    Segmentation2D(scan_id=, upstream_task=Undistorted, model_fileset=ModelFileset, model_id=Resnet_896_896_epoch50, query={"channel": "rgb"}, Sx=896, Sy=896, labels=[], inverted_labels=["background"], binarize=True, threshold=0.01, dilation=1) from fileConfig
Traceback (most recent call last):
  File "/home/scanner/.local/lib/python3.7/site-packages/luigi/worker.py", line 191, in run
    new_deps = self._run_get_new_deps()
  File "/home/scanner/.local/lib/python3.7/site-packages/luigi/worker.py", line 133, in _run_get_new_deps
    task_gen = self.task.run()
  File "/home/scanner/.local/lib/python3.7/site-packages/plant3dvision/tasks/proc2d.py", line 201, in run
    images_segmented, id_im = segmentation(self.Sx, self.Sy, images_fileset, model_file)
  File "/home/scanner/plant-3d-vision/romiseg/romiseg/Segmentation2D.py", line 101, in segmentation
    outputs = evaluate(inputs, model_segmentation)  #output image
File "/home/scanner/plant-3d-vision/romiseg/romiseg/utils/train_from_dataset.py", line 546, in evaluate
    pred = model(inputs)
  File "/home/scanner/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/scanner/plant-3d-vision/romiseg/romiseg/utils/segmentation_model.py", line 116, in forward
    x = torch.cat([x, x_original], dim=1)
RuntimeError: CUDA out of memory. Tried to allocate 588.00 MiB (GPU 0; 11.17 GiB total capacity; 8.04 GiB already allocated; 517.31 MiB free; 10.21 GiB reserved in total by PyTorch)
INFO     [luigi-interface] Informed scheduler that task   Segmentation2D_896_896_True_666a04139b   has status   FAILED from fileConfig
INFO     [luigi-interface] Worker Worker(salt=351061715, workers=1, host=9d606809db6a, username=scanner, pid=1837) was stopped. Shutting down Keep-Alive thread from fileConfig
INFO     [luigi-interface] 
===== Luigi Execution Summary =====
Scheduled 10 tasks of which:
* 2 complete ones were encountered:
    - 1 ImagesFilesetExists(scan_id=, fileset_id=images)
    - 1 ModelFileset(scan_id=models)
* 2 ran successfully:
    - 1 Colmap(...)
    - 1 Undistorted(scan_id=, query={}, upstream_task=ImagesFilesetExists)
* 1 failed:
    - 1 Segmentation2D(...)
* 5 were left pending, among these:
    * 5 had failed dependencies:
        - 1 AnglesAndInternodes(...)
        - 1 OrganSegmentation(scan_id=, upstream_task=SegmentedPointCloud, eps=2.0, min_points=5)
        - 1 PointCloud(...)
        - 1 SegmentedPointCloud(scan_id=, upstream_task=PointCloud, upstream_segmentation=Segmentation2D, use_colmap_poses=True)
        - 1 Voxels(...)
This progress looks :( because there were failed tasks
===== Luigi Execution Summary =====
 from fileConfig
cuda:0
tensor(2.6400)
tensor(2.6400)
tensor(2.6400)
tensor(2.6400)
tensor(2.6400)
tensor(2.6400)
tensor(2.6400)
tensor(2.6400)
tensor(2.6400)
tensor(2.6400)
tensor(2.6400)
tensor(2.6400)
tensor(2.6400)
tensor(2.6400)
tensor(2.6400)
tensor(2.6400)
tensor(2.6400)
tensor(2.6400)
tensor(2.6400)
tensor(2.6400)
tensor(2.6400)
tensor(2.6400)
tensor(2.6400)
tensor(2.6400)
tensor(2.6400)
tensor(2.6400)
tensor(2.6400)
tensor(2.6400)
tensor(2.6400)
tensor(2.6400)
tensor(2.6400)
tensor(2.6400)
Traceback (most recent call last):
 File "/home/scanner/.local/bin/romi_run_task", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/scanner/plant-3d-vision/romitask/bin/romi_run_task", line 212, in <module>
    subprocess.run(cmd, env={**os.environ, **env}, check=True)
  File "/usr/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['luigi', '--logging-conf-file', '/tmp/tmpxn9taa2b/logging_config.toml', '--module', 'plant3dvision.tasks.arabidopsis', 'AnglesAndInternodes', '--DatabaseConfig-scan', 'database/Sangoku_mlpipe_1', '--local-scheduler']' returned non-zero exit status 30.
(END)
```
